### ISSUE TITLE
Fails to build on zig 0.16 macos

### ISSUE THREAD

**Issue by tacheraSasi** [Mario-SO/cronos#3]
ib/cronos/clock.zig:6:29: error: root source file struct 'time' has no member named 'timestamp'
    const seconds = std.time.timestamp();
                    ~~~~~~~~^~~~~~~~~~
/usr/local/zig/lib/std/time.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    init: src/app/state.zig:168:55
    init: src/main.zig:20:19
    5 reference(s) hidden; use '-freference-trace=7' to see all references
error: 1 compilation errors
